### ISSUE TITLE
Missing Gentoo Bugzilla account for the overlay (and missing masters=)

### ISSUE THREAD

**Issue by mgorny** [arax-os/overlay#6]
https://bugs.gentoo.org/show_bug.cgi?id=552958

Please provide us with a working Bugzilla account so we could file bugs against your overlay. And while at it, please fix the linked issue :).

**Comment by arax-os** [comment]
merged: https://github.com/arax-os/overlay/commit/0b00370ff9fb65269499e0e719be71a65b885dd6

thank you for opening an issue.
